Repository sockethub/sockethub, pull requests merged in 2020-07, with the labels that each got.

#258 Switch from node.js domains to child process
  packages/sockethub-platform-xmpp/index.js
  packages/sockethub-platform-xmpp/package.json
  packages/sockethub/bin/sockethub
  packages/sockethub/dist/bootstrap/platforms.js
  packages/sockethub/dist/bootstrap/platforms.js.map
  packages/sockethub/dist/common.js
  packages/sockethub/dist/common.js.map
  packages/sockethub/dist/crypto.js
  packages/sockethub/dist/crypto.js.map
  packages/sockethub/dist/platform-instance.js
  packages/sockethub/dist/platform-instance.js.map
  packages/sockethub/dist/platform.js
  packages/sockethub/dist/platform.js.map
  packages/sockethub/dist/process-manager.js
  packages/sockethub/dist/process-manager.js.map
  packages/sockethub/dist/resource-manager.js
  packages/sockethub/dist/resource-manager.js.map
  packages/sockethub/dist/routes/examples.js
  packages/sockethub/dist/routes/examples.js.map
  packages/sockethub/dist/services.js
  packages/sockethub/dist/services.js.map
  packages/sockethub/dist/shared-resources.js
  packages/sockethub/dist/shared-resources.js.map
  packages/sockethub/dist/sockethub.js
  packages/sockethub/dist/sockethub.js.map
  packages/sockethub/dist/validate.js
  packages/sockethub/dist/validate.js.map
  packages/sockethub/dist/worker.js
  packages/sockethub/dist/worker.js.map
  packages/sockethub/package.json
  packages/sockethub/src/bootstrap/platforms.js
  packages/sockethub/src/common.ts
  packages/sockethub/src/crypto.ts
  packages/sockethub/src/platform-instance.ts
  packages/sockethub/src/platform.ts
  packages/sockethub/src/process-manager.ts
  packages/sockethub/src/resource-manager.ts
  packages/sockethub/src/shared-resources.d.ts
  packages/sockethub/src/shared-resources.ts
  packages/sockethub/src/sockethub.ts
  packages/sockethub/src/validate.ts
  packages/sockethub/src/worker.d.ts
  packages/sockethub/src/worker.ts
  packages/sockethub/test/shared-resources-suite.js
  packages/sockethub/views/examples/xmpp.ejs
  packages/sockethub/yarn.lock
Labels: enhancement, in progress, kredits-3, ready

#273 dependency version bumps
  packages/activity-streams.js/yarn.lock
  packages/irc2as/yarn.lock
  packages/sockethub-platform-dummy/yarn.lock
  packages/sockethub-platform-feeds/yarn.lock
  packages/sockethub-platform-irc/yarn.lock
  packages/sockethub-platform-xmpp/yarn.lock
  packages/sockethub-schemas/yarn.lock
  packages/sockethub/yarn.lock
  yarn.lock
Labels: kredits-1

#274 update major versions for build tasks
  packages/activity-streams.js/package.json
  packages/activity-streams.js/yarn.lock
  packages/sockethub-platform-feeds/package-lock.json
  packages/sockethub-platform-feeds/package.json
  packages/sockethub-platform-feeds/yarn.lock
  packages/sockethub-platform-irc/package.json
  packages/sockethub-platform-irc/yarn.lock
  packages/sockethub-platform-xmpp/package.json
  packages/sockethub-platform-xmpp/yarn.lock
  packages/sockethub/package.json
  packages/sockethub/yarn.lock
Labels: kredits-1

#275 Remove all platform instances when main process exits
  packages/sockethub/bin/sockethub
  packages/sockethub/src/sockethub.ts
Labels: kredits-2
