Repository sockethub/sockethub, pull requests merged in 2021-04, with the labels that each got.

#356 Pass complete job object to handleJobResult method
  packages/sockethub/src/platform-instance.ts
Labels: bug, kredits-1, ready

#359 bugfix: required param to Bulls clean method
  packages/sockethub/src/platform-instance.ts
Labels: bug, kredits-1, ready

#357 Remove references to simple-xmpp
  packages/sockethub-platform-xmpp/API.md
  packages/sockethub-platform-xmpp/package.json
  packages/sockethub-platform-xmpp/src/index.js
  packages/sockethub-platform-xmpp/yarn.lock
Labels: kredits-1, ready, technical debt

#358 Update dependencies
  package.json
  packages/activity-streams.js/yarn.lock
  packages/irc2as/yarn.lock
  packages/sockethub-platform-irc/yarn.lock
  packages/sockethub/package.json
  packages/sockethub/yarn.lock
  yarn.lock
Labels: dependencies, kredits-1, ready

#362 Add metadata to incoming XMPP messages
  packages/sockethub-platform-xmpp/src/incoming-handlers.js
  packages/sockethub-platform-xmpp/src/incoming-handlers.test.js
Labels: kredits-2, platform-xmpp

#361 Update jsdoc
  packages/sockethub-platform-feeds/API.md
  packages/sockethub-platform-feeds/package.json
  packages/sockethub-platform-feeds/yarn.lock
  packages/sockethub-platform-irc/API.md
  packages/sockethub-platform-irc/index.js
  packages/sockethub-platform-irc/package.json
  packages/sockethub-platform-irc/yarn.lock
  packages/sockethub-platform-xmpp/API.md
  packages/sockethub-platform-xmpp/package.json
  packages/sockethub-platform-xmpp/src/index.js
  packages/sockethub-platform-xmpp/yarn.lock
  packages/sockethub/src/platform.ts
Labels: kredits-2, platform-feeds, platform-irc, platform-xmpp, technical debt

#360 Improve typing
  packages/sockethub-platform-irc/yarn.lock
  packages/sockethub/src/common.ts
  packages/sockethub/src/middleware.ts
  packages/sockethub/src/platform-instance.test.ts
  packages/sockethub/src/platform-instance.ts
  packages/sockethub/src/platform.ts
  packages/sockethub/src/services.d.ts
  packages/sockethub/src/sockethub.ts
  packages/sockethub/yarn.lock
Labels: enhancement, kredits-2

#364 Update docker files
  Dockerfile
  docker-compose.yml
Labels: kredits-1
