Repository sockethub/sockethub, pull requests merged in 2021-08, with the labels that each got.

#514 Fix location references in package.json
  packages/activity-streams.js/package.json
  packages/irc2as/package.json
  packages/sockethub-platform-dummy/package.json
  packages/sockethub-platform-feeds/package.json
  packages/sockethub-platform-irc/package.json
  packages/sockethub-platform-xmpp/package.json
  packages/sockethub-schemas/package.json
  packages/sockethub/package.json
Labels: ready, kredits-1

#508 Unify coverage and set thresholds
  packages/activity-streams.js/package.json
  packages/activity-streams.js/yarn.lock
  packages/irc2as/package.json
  packages/sockethub-platform-irc/package.json
  packages/sockethub-platform-xmpp/package.json
  packages/sockethub-platform-xmpp/yarn.lock
  packages/sockethub-schemas/package.json
  packages/sockethub-schemas/yarn.lock
  packages/sockethub/package.json
  packages/sockethub/yarn.lock
Labels: enhancement, ready, kredits-2

#518 Fix polynominal time required to match regexp
  packages/sockethub-platform-irc/index.js
Labels: bug, ready, kredits-1

#515 Improve coverage & raise coverage threshold
  packages/activity-streams.js/karma.config.js
  packages/activity-streams.js/package.json
  packages/activity-streams.js/src/activity-streams.js
  packages/activity-streams.js/src/activity-streams.test.js
  packages/activity-streams.js/webpack.config.js
  packages/sockethub/package.json
  packages/sockethub/src/common.test.ts
Labels: ready, kredits-2

#523 Fix broken linting
  package.json
  packages/sockethub-platform-irc/index.js
  packages/sockethub/src/common.test.ts
  packages/sockethub/src/crypto.test.ts
  packages/sockethub/src/platform-instance.test.ts
  packages/sockethub/src/routes.test.ts
  packages/sockethub/src/store.test.ts
Labels: bug, ready, kredits-1

#524 Remove support for node 15
  .github/workflows/compliance.yml
Labels: ready, kredits-1, technical debt

#522 Keep client event handlers stored in an array
  packages/sockethub/src/js/client.js
Labels: bug, ready, kredits-1

#521 Add route to generated source map for sockethub-client
  packages/sockethub/src/js/sockethub-client.js
  packages/sockethub/src/routes.test.ts
  packages/sockethub/src/routes.ts
  packages/sockethub/tsconfig.json
Labels: enhancement, ready, kredits-1

#532 Fix/update Docker setup
  Dockerfile
  docker-compose.yml
Labels: ready, kredits-1, technical debt

#553 XMPP credentials `server` property no longer required
  packages/sockethub-platform-xmpp/src/schema.js
Labels: type:bug, state:ready, kredits-1, package:platform-xmpp

#554 Added linting checks for common node security vectors
  .eslintrc
  package.json
  packages/sockethub/bin/sockethub
  packages/sockethub/src/bootstrap/init.ts
  packages/sockethub/src/platform.ts
  yarn.lock
Labels: state:ready, kredits-1

#517 Improved Middleware
  packages/sockethub/package.json
  packages/sockethub/src/middleware.test.ts
  packages/sockethub/src/middleware.ts
  packages/sockethub/src/middleware/create-activity-object.test.ts
  packages/sockethub/src/middleware/create-activity-object.ts
  packages/sockethub/src/middleware/store-credentials.test.ts
  packages/sockethub/src/middleware/store-credentials.ts
  packages/sockethub/src/middleware/validate.d.ts
  packages/sockethub/src/middleware/validate.test.data.ts
  packages/sockethub/src/middleware/validate.test.ts
  packages/sockethub/src/middleware/validate.ts
  packages/sockethub/src/sockethub.ts
  packages/sockethub/test/validate-suite.js
  packages/sockethub/tsconfig.json
  packages/sockethub/views/examples/feeds.ejs
Labels: type:feature, state:ready, kredits-2, package:core

#516 Feeds: Fix results not being sent back correctly
  packages/sockethub-platform-feeds/index.js
  packages/sockethub/src/middleware.ts
  packages/sockethub/src/middleware/validate.ts
  packages/sockethub/src/platform-instance.ts
  packages/sockethub/src/platform.ts
Labels: type:bug, state:ready, kredits-1, package:platform-feeds

#560 Github Actions: split linting and unit tests
  .github/workflows/compliance.yml
  package.json
  packages/activity-streams.js/package.json
  packages/irc2as/package.json
  packages/sockethub-platform-feeds/package.json
  packages/sockethub-platform-irc/package.json
  packages/sockethub-platform-xmpp/package.json
  packages/sockethub-schemas/package.json
  packages/sockethub/package.json
Labels: state:ready, kredits-2, type:technical-debt, info:infrastructure

#559 Update renovate config
  .github/renovate.json
Labels: state:ready, kredits-1, type:technical-debt, info:infrastructure

#538 Fix redis options not passing to bull#Queue
  packages/sockethub/src/platform-instance.ts
  packages/sockethub/src/platform.ts
Labels: type:bug, kredits-2, state:blocker, package:core

#562 Safely parse resultString
  packages/sockethub/src/platform-instance.ts
Labels: type:bug, state:ready, kredits-1, package:core

#561 Fix build and dist files
  packages/sockethub/package.json
  packages/sockethub/src/client/sockethub-client.js
  packages/sockethub/src/routes.test.ts
  packages/sockethub/src/routes.ts
  packages/sockethub/yarn.lock
Labels: type:bug, state:ready, kredits-1, package:core

#565 XMPP Presence `unavailable`
  packages/sockethub-platform-xmpp/src/incoming-handlers.data.js
  packages/sockethub-platform-xmpp/src/incoming-handlers.js
  packages/sockethub-platform-xmpp/src/incoming-handlers.test.js
Labels: type:bug, state:ready, kredits-2, package:platform-xmpp
