Repository sockethub/sockethub, pull requests merged in 2021-12, with the labels that each got.

#640 Replace old 'set' type with 'credentials' in examples
  packages/sockethub-platform-irc/API.md
  packages/sockethub-platform-irc/index.js
  packages/sockethub-platform-xmpp/API.md
  packages/sockethub-platform-xmpp/src/index.js
Labels: info:documentation, kredits-1

#644 Remove old typing for kue
  packages/sockethub/package.json
Labels: state:ready, type:dependencies

#645 Update renovate.json
  .github/renovate.json
Labels: state:ready, kredits-1, type:dependencies

#641 Improve schema coverage for existing object types
  packages/sockethub-platform-irc/index.js
  packages/sockethub-platform-xmpp/src/index.js
  packages/sockethub-schemas/index.js
  packages/sockethub-schemas/package.json
  packages/sockethub-schemas/schemas/activity-object.js
  packages/sockethub-schemas/schemas/activity-object.json
  packages/sockethub-schemas/schemas/activity-stream.js
  packages/sockethub-schemas/schemas/activity-stream.json
  packages/sockethub-schemas/src/object-types.js
  packages/sockethub-schemas/src/util.js
  packages/sockethub-schemas/tests/schemas.test.data.js
  packages/sockethub-schemas/tests/schemas.test.js
  packages/sockethub/src/middleware/validate.test.data.ts
  packages/sockethub/src/middleware/validate.test.ts
  packages/sockethub/src/middleware/validate.ts
Labels: state:ready, kredits-2, package:schemas

#648 Update irc2as to use new property names
  packages/irc2as/as-emitter.js
  packages/irc2as/index.js
  packages/irc2as/test/test-suite.js
  packages/sockethub-platform-irc/API.md
  packages/sockethub-platform-irc/index.js
  packages/sockethub-platform-xmpp/API.md
  packages/sockethub-platform-xmpp/src/index.js
Labels: type:bug, state:ready, kredits-1

#651 Add user-generated ID to outgoing XMPP messages
  packages/sockethub-platform-xmpp/src/index.js
  packages/sockethub-platform-xmpp/src/index.test.js
Labels: kredits-1

#649 Support incoming message correction for XMPP messages
  packages/sockethub-platform-xmpp/src/incoming-handlers.data.js
  packages/sockethub-platform-xmpp/src/incoming-handlers.js
  packages/sockethub-platform-xmpp/src/index.js
  packages/sockethub-platform-xmpp/src/index.test.js
Labels: type:feature, kredits-1, package:platform-xmpp
