Repository sockethub/sockethub, pull requests merged in 2021-02, with the labels that each got.

#318 [xmpp] Tests for incoming stanzas
  packages/sockethub-platform-xmpp/jest.config.js
  packages/sockethub-platform-xmpp/src/incoming-handlers.js
  packages/sockethub-platform-xmpp/src/incoming-handlers.test.js
  packages/sockethub-platform-xmpp/src/index.js
  packages/sockethub-platform-xmpp/src/index.test.js
  packages/sockethub-platform-xmpp/test/incoming-data.js
  packages/sockethub-platform-xmpp/test/incoming-handlers-suite.js
Labels: kredits-2, ready, technical debt

#324 ignore package-lock.json
  .gitignore
Labels: kredits-1, ready, technical debt

#322 Use irc-socket Tls fix from silverbucket/irc-socket
  packages/sockethub-platform-irc/index.js
  packages/sockethub-platform-irc/package.json
  packages/sockethub-platform-irc/yarn.lock
  packages/sockethub/views/examples/irc.ejs
  yarn.lock
Labels: bug, kredits-2, platform-irc, ready

#328 Remove dist folder from version control
  .gitignore
  packages/sockethub/dist/bootstrap/init.js
  packages/sockethub/dist/bootstrap/init.js.map
  packages/sockethub/dist/bootstrap/platforms.js
  packages/sockethub/dist/bootstrap/platforms.js.map
  packages/sockethub/dist/common.js
  packages/sockethub/dist/common.js.map
  packages/sockethub/dist/config.js.map
  packages/sockethub/dist/crypto.js
  packages/sockethub/dist/crypto.js.map
  packages/sockethub/dist/defaults.json
  packages/sockethub/dist/js/client.js
  packages/sockethub/dist/js/client.js.map
  packages/sockethub/dist/middleware.js
  packages/sockethub/dist/middleware.js.map
  packages/sockethub/dist/platform-instance.js
  packages/sockethub/dist/platform-instance.js.map
  packages/sockethub/dist/platform-instance.test.js
  packages/sockethub/dist/platform-instance.test.js.map
  packages/sockethub/dist/platform.js
  packages/sockethub/dist/platform.js.map
  packages/sockethub/dist/process-manager.js
  packages/sockethub/dist/process-manager.js.map
  packages/sockethub/dist/resource-manager.js
  packages/sockethub/dist/resource-manager.js.map
  packages/sockethub/dist/routes/base.js
  packages/sockethub/dist/routes/base.js.map
  packages/sockethub/dist/routes/examples.js
  packages/sockethub/dist/routes/examples.js.map
  packages/sockethub/dist/services.js
  packages/sockethub/dist/services.js.map
  packages/sockethub/dist/shared-resources.js
  packages/sockethub/dist/shared-resources.js.map
  packages/sockethub/dist/shared-resources.test.js
  packages/sockethub/dist/shared-resources.test.js.map
  packages/sockethub/dist/sockethub.js
  packages/sockethub/dist/sockethub.js.map
  packages/sockethub/dist/validate.js
  packages/sockethub/dist/validate.js.map
Labels: kredits-1, ready, technical debt

#329 Update lockfiles
  packages/sockethub-platform-irc/yarn.lock
  yarn.lock
Labels: dependencies, kredits-1, technical debt

#333 Ensure config is only loaded once per thread
  packages/sockethub/src/config.ts
Labels: kredits-1, ready, technical debt

#332 Add debug logging toggle to SockethubClient
  packages/sockethub/src/js/client.js
Labels: enhancement, kredits-1, ready

#330 Logging improvements
  packages/sockethub-platform-irc/index.js
  packages/sockethub/src/platform.ts
  packages/sockethub/src/sockethub.ts
  packages/sockethub/src/validate.ts
Labels: enhancement, kredits-1, ready, technical debt

#327 Fix socket.io breaking change (CORS issue)
  packages/sockethub/package.json
  packages/sockethub/yarn.lock
Labels: bug, dependencies, kredits-1, ready

#340 Add yarn/npm script for ESLint
  README.md
  package.json
Labels: kredits-1

#341 Fix client exception when AS object has no target
  packages/sockethub/src/js/client.js
Labels: bug, kredits-1
