Repository sockethub/sockethub, pull requests merged in 2022-01, with the labels that each got.

#653 Support outgoing message correction
  packages/sockethub-platform-xmpp/src/index.js
  packages/sockethub-platform-xmpp/src/index.test.js
Labels: kredits-1

#596 Refactor sockethub-client
  packages/activity-streams.js/browser/activity-streams.min.js
  packages/sockethub-platform-irc/yarn.lock
  packages/sockethub-platform-xmpp/src/index.js
  packages/sockethub/bin/sockethub
  packages/sockethub/package.json
  packages/sockethub/src/client/sockethub-client.js
  packages/sockethub/src/janitor.ts
  packages/sockethub/src/middleware.test.ts
  packages/sockethub/src/middleware.ts
  packages/sockethub/src/platform-instance.test.ts
  packages/sockethub/src/platform-instance.ts
  packages/sockethub/src/platform.ts
  packages/sockethub/src/process-manager.ts
  packages/sockethub/src/routes.ts
  packages/sockethub/src/sockethub-client.test.ts
  packages/sockethub/src/sockethub-client.ts
  packages/sockethub/src/sockethub.ts
  packages/sockethub/views/examples/irc.ejs
  packages/sockethub/views/examples/shared.js
  packages/sockethub/views/examples/xmpp.ejs
  packages/sockethub/webpack.minified.config.js
  packages/sockethub/webpack.normal.config.js
  packages/sockethub/yarn.lock
  yarn.lock
Labels: state:ready, kredits-3, type:technical-debt, package:core, info:breaking-change

#498 Integration Tests - Github Actions
  .github/workflows/compliance.yml
  .github/workflows/integration.yml
  Dockerfile
  docker-compose.yml
  karma.config.js
  package.json
  packages/activity-streams.js/browser/activity-streams.min.js
  packages/activity-streams.js/package.json
  packages/activity-streams.js/src/activity-streams.js
  packages/activity-streams.js/yarn.lock
  packages/irc2as/package.json
  packages/irc2as/yarn.lock
  packages/sockethub-platform-irc/package.json
  packages/sockethub-platform-irc/yarn.lock
  packages/sockethub-platform-xmpp/package.json
  packages/sockethub-platform-xmpp/src/utils.js
  packages/sockethub-platform-xmpp/yarn.lock
  packages/sockethub-schemas/package.json
  packages/sockethub-schemas/yarn.lock
  packages/sockethub/package.json
  packages/sockethub/src/platform.ts
  packages/sockethub/yarn.lock
  test/README.md
  test/prosody/prosody.cfg.lua
  test/xmpp.test.js
  yarn.lock
Labels: state:ready, kredits-3, info:infrastructure
